# NUMPY III: Operaciones estadísticas y matemáticas

En esta lección hemos aprendido algunas de las operaciones matemáticas más importantes que podemos aplicar a un array. Hoy pondremos en práctica algunas de estas operaciones, además de recordar algunas de los métodos aprendidos en otras lecciones y recordar como podemos iterar por un array.

In [1]:
import numpy as np

### 1. Cread un array de tres dimensiones de 2 matrices, 3 filas y 5 columnas cuyos valores solo tengan 1 decimales. Sobre el array creado anteriormente, extraed:

In [5]:
array1 = np.random.rand(2,3,5)
array2 = np.round(array1, decimals = 1)
array2

array([[[0.3, 0.3, 0.7, 0. , 0.2],
        [0.4, 1. , 0.8, 0.6, 0.1],
        [0.2, 0.1, 0.1, 0.5, 0.2]],

       [[0.1, 0.1, 0.2, 0.4, 0.8],
        [1. , 0.1, 0.5, 0.4, 0.6],
        [0.8, 0.8, 0.5, 0.5, 0.1]]])

### 2. Calculad la media del array y almacenarlos en una variable. Redondead a un decimal.

In [24]:
media = np.mean(array2)
media = np.round(media, decimals = 1)

media

0.4

### 3. Calculad el valor máximo del array y almacenarlos en una variable. Redondead a un decimal.

In [25]:
maximo = np.max(array2)
maximo = np.round(maximo, decimals = 1)

maximo

1.0

### 4. Calculad el valor mínimo del array y almacenarlos en una variable. Redondead a un decimal.

In [26]:
minimo = np.min(array2)
minimo = np.round(minimo, decimals = 1)

minimo

0.0

### 5. Cread un array vacío con la misma forma y dimensiones que el array creado anteriormente. 

Vamos a reemplazar los valores de la matriz vacía que nos acabamos de crear pero basándonos en los valores del primer array bajo las siguientes condiciones:

In [17]:
array3 = np.empty((2,3,5), str)
array3

array([[['', '', '', '', ''],
        ['', '', '', '', ''],
        ['', '', '', '', '']],

       [['', '', '', '', ''],
        ['', '', '', '', ''],
        ['', '', '', '', '']]], dtype='<U1')

- Si el valor del array es igual que la media, se reemplaza por "A".
- Si el valor del array es mayor que la media, se reemplaza por "B".
- Si el valor del array es menor que la media, se reemplaza por "C".
- Si el valor es igual que el máximo, se reemplaza por "D".
- Si el valor es igual que el mínimo, se reemplaza por "E".

In [36]:
forma = array2.shape
forma

(2, 3, 5)

In [54]:
for m in range(0,forma[0]):
    for f in range(0,forma[1]):
        for e in range(0,forma[2]):
            if array2[m,f,e] == media:
                array3[m,f,e] = "A"
            elif array2[m,f,e] > media:
                array3[m,f,e] = "B"
            elif array2[m,f,e] < media:
                array3[m,f,e] = "C"
            elif array2[m, f, e] == maximo:
                array3[m,f,e] = "D"
            elif array2[m,f,e] == minimo:
                array3[m,f,e] = "E"
print(array3)
        

[[['C' 'C' 'B' 'C' 'C']
  ['A' 'B' 'B' 'B' 'C']
  ['C' 'C' 'C' 'B' 'C']]

 [['C' 'C' 'C' 'A' 'B']
  ['B' 'C' 'B' 'A' 'B']
  ['B' 'B' 'B' 'B' 'C']]]


💡 Pista 💡 Tendréis que iterar por el array y cambiar los valores de la matriz vacía. Para eso tendremos que usar distintos condicionales.

### 6. Estupendo, tenemos un array con strings. Ahora realizaremos un ejercicio similar al anterior, pero en este caso nos crearemos un array vacío unidimensional de 30 elementos. Al final de este ejercicio acabaremos teniendo un array de tres dimensiones con la misma forma que el primero que nos creamos.
En este caso:

In [64]:
array4 = np.empty(30)
array4

array([3.10503618e+231, 3.10503618e+231, 7.90505033e-323, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       4.24399158e-314, 0.00000000e+000, 3.10503618e+231, 3.10503618e+231,
       6.92752000e-310, 6.92752481e-310, 6.92752000e-310, 6.92752481e-310,
       6.92751696e-310, 6.92752000e-310])

In [63]:
array3

array([[['C', 'C', 'B', 'C', 'C'],
        ['A', 'B', 'B', 'B', 'C'],
        ['C', 'C', 'C', 'B', 'C']],

       [['C', 'C', 'C', 'A', 'B'],
        ['B', 'C', 'B', 'A', 'B'],
        ['B', 'B', 'B', 'B', 'C']]], dtype='<U1')

- Si el valor del array creado en el ejercicio anterior es "A" o "B" lo reemplazaremos por 1.
- Si el valor del array creado en el ejercicio anterior es "C" o "D" lo reemplazaremos por 2.
- Si el valor del array creado en el ejercicio anterior es "E" lo reemplazaremos por 3.

In [76]:
contador = 0

for m in range(0,forma[0]):
    for f in range(0,forma[1]):
        for e in range(0,forma[2]):
            if array3[m,f,e] == 'A' or array3[m,f,e] == 'B':
                array4[contador] = 1
            elif array3[m,f,e] == 'C' or array3[m,f,e] == 'D':
                array4[contador] = 2
            elif array3[m,f,e] == 'E':
                array4[contador] = 3
            contador += 1
print(array4)

[2. 2. 1. 2. 2. 1. 1. 1. 1. 2. 2. 2. 2. 1. 2. 2. 2. 2. 1. 1. 1. 2. 1. 1.
 1. 1. 1. 1. 1. 2.]


Una vez que hayas reemplazado todos los valores cambiad la forma del array para que sea de tres dimensiones, con 2 matrices, 3 filas y 5 columnas.
Happy coding 😀

In [77]:
array4.reshape(2,3,5)

array([[[2., 2., 1., 2., 2.],
        [1., 1., 1., 1., 2.],
        [2., 2., 2., 1., 2.]],

       [[2., 2., 2., 1., 1.],
        [1., 2., 1., 1., 1.],
        [1., 1., 1., 1., 2.]]])