In [1]:
import numpy as np

1. Cread un array de dos dimensiones de 5 filas y 3 columnas. Sobre el array creado anteriormente, extraed:
- El valor de la primera fila y la segunda columna.

In [7]:
array1 = np.random.rand(5,3)
array1

array([[0.95666633, 0.00373514, 0.37219223],
       [0.06835723, 0.07337029, 0.7071743 ],
       [0.80347646, 0.86214162, 0.15553448],
       [0.98926936, 0.61657518, 0.07589783],
       [0.84366774, 0.12257471, 0.31173096]])

In [8]:
array1[0,1]

0.003735141243536799

- Los valores de la segunda fila y las dos primeras columnas.

In [9]:
array1[1,:2]

array([0.06835723, 0.07337029])

- Extraed las filas pares (incluyendo la 0) y todas las columnas.

In [10]:
array1[::2,:]

array([[0.95666633, 0.00373514, 0.37219223],
       [0.80347646, 0.86214162, 0.15553448],
       [0.84366774, 0.12257471, 0.31173096]])

- Extraed los valores que sean mayores que 0.5.

In [11]:
array1[(array1 > 0.5)]

array([0.95666633, 0.7071743 , 0.80347646, 0.86214162, 0.98926936,
       0.61657518, 0.84366774])

- Extraed los valores menores que 0.2 o mayores que 0.5

In [12]:
array1[(array1 < 0.2) | (array1 > 0.5)]

array([0.95666633, 0.00373514, 0.06835723, 0.07337029, 0.7071743 ,
       0.80347646, 0.86214162, 0.15553448, 0.98926936, 0.61657518,
       0.07589783, 0.84366774, 0.12257471])

2. Cread dos array de tres dimensiones:
- El primero de 2 matrices, 5 filas y 3 columnas.

In [13]:
array2 = np.random.randint(0,100, (2,5,3))
array2

array([[[97,  4, 35],
        [12, 33, 14],
        [28, 36, 62],
        [73, 76, 86],
        [54, 13, 64]],

       [[10,  8, 56],
        [47, 62, 86],
        [15, 21, 38],
        [66,  1, 95],
        [ 9, 55, 78]]])

- El segundo de 3 matrices, 2 filas y 5 columnas

In [14]:
array3 = np.random.randint(0,100, (3,2,5))
array3

array([[[61, 15, 20, 87, 23],
        [ 0, 97, 17, 33, 14]],

       [[89, 63, 17, 67, 73],
        [44, 30, 58, 75, 65]],

       [[29, 63, 14, 76, 80],
        [49, 48, 68, 72,  0]]])

- Haced un análisis exploratorio de los array creados. Recordad que en el ejercicio de ayer nos creamos una función para esto.

In [15]:
def propiedades(array):
    lista_propiedades = []
    lista_propiedades.append(array.shape)
    lista_propiedades.append(array.size)
    lista_propiedades.append(array.ndim)
    lista_propiedades.append(array.dtype)
    return lista_propiedades

In [18]:
print(f"El orden de las propiedades descritas, es forma, tamaño, dimension y tipo:", propiedades(array2))

El orden de las propiedades descritas, es forma, tamaño, dimension y tipo: [(2, 5, 3), 30, 3, dtype('int64')]


In [19]:
print(f"El orden de las propiedades descritas, es forma, tamaño, dimension y tipo:", propiedades(array3))

El orden de las propiedades descritas, es forma, tamaño, dimension y tipo: [(3, 2, 5), 30, 3, dtype('int64')]


- Sumad los dos arrays. ¿Podéis? ¿Por qué?

In [20]:
np.add(array2, array3)

ValueError: operands could not be broadcast together with shapes (2,5,3) (3,2,5) 

No podemos sumarlos ya que como vemos en el paso anterior tienen distinta forma, (2,5,3) y (3,2,5)

- Para cambiar la forma de un array y poder hacer operaciones entre arrays que tienen distintas formas hemos aprendido dos métodos:
.reshape()

In [21]:
array4 = array3.reshape(2,5,3)
array4

array([[[61, 15, 20],
        [87, 23,  0],
        [97, 17, 33],
        [14, 89, 63],
        [17, 67, 73]],

       [[44, 30, 58],
        [75, 65, 29],
        [63, 14, 76],
        [80, 49, 48],
        [68, 72,  0]]])

In [22]:
np.add(array2, array4)

array([[[158,  19,  55],
        [ 99,  56,  14],
        [125,  53,  95],
        [ 87, 165, 149],
        [ 71,  80, 137]],

       [[ 54,  38, 114],
        [122, 127, 115],
        [ 78,  35, 114],
        [146,  50, 143],
        [ 77, 127,  78]]])

.transpose()
Utiliza estas dos funciones para cambiar la forma de los array y hacer operaciones entre ellos.

In [24]:
array5 = np.transpose(array3, (1,2,0))
array5

array([[[61, 89, 29],
        [15, 63, 63],
        [20, 17, 14],
        [87, 67, 76],
        [23, 73, 80]],

       [[ 0, 44, 49],
        [97, 30, 48],
        [17, 58, 68],
        [33, 75, 72],
        [14, 65,  0]]])

In [25]:
np.add(array2, array5)

array([[[158,  93,  64],
        [ 27,  96,  77],
        [ 48,  53,  76],
        [160, 143, 162],
        [ 77,  86, 144]],

       [[ 10,  52, 105],
        [144,  92, 134],
        [ 32,  79, 106],
        [ 99,  76, 167],
        [ 23, 120,  78]]])