# NUMPY IV: Conjuntos, distribuciones aleatorias

Manos a la obra con la última lección de NumPy. En este caso pondremos en práctica como generar arrays que sigan ciertas distribuciones, así como las operaciones de teoría de conjuntos básicas.

In [2]:
import numpy as np

### 1. ¿Cómo podemos crear dos arrays de dos dimensiones usando el método random_sample que tengan los mismos valores?

In [22]:
# Para que los arrays tengan los mismos valores tenemos que utilizar primero el método seed
np.random.seed(2)
array = np.random.random_sample((3,5))
array

array([[0.4359949 , 0.02592623, 0.54966248, 0.43532239, 0.4203678 ],
       [0.33033482, 0.20464863, 0.61927097, 0.29965467, 0.26682728],
       [0.62113383, 0.52914209, 0.13457995, 0.51357812, 0.18443987]])

In [23]:
np.random.seed(2)
array0 = np.random.random_sample((3,5))
array0

array([[0.4359949 , 0.02592623, 0.54966248, 0.43532239, 0.4203678 ],
       [0.33033482, 0.20464863, 0.61927097, 0.29965467, 0.26682728],
       [0.62113383, 0.52914209, 0.13457995, 0.51357812, 0.18443987]])

### 2. Cread los siguientes arrays:
- Un array de tres dimensiones con distribución uniforme de 2 x 3 x 5, con números entre 0 y 10, que no tengan decimales y extrae sus valores únicos almacenándolos en una variable.

In [28]:
arr3 = np.random.uniform(low = 0, high = 10, size = (2,3,5))
arr3 = np.round(arr3, decimals = 0)
arr3

array([[[ 5.,  7.,  2.,  2.,  1.],
        [ 3.,  0.,  6.,  3.,  2.],
        [ 1.,  3.,  2.,  3.,  5.]],

       [[ 5.,  8., 10.,  0.,  2.],
        [ 6.,  2.,  9.,  2.,  7.],
        [ 7.,  8.,  0.,  2.,  7.]]])

In [29]:
arr3_unicos = np.unique(arr3)
arr3_unicos

array([ 0.,  1.,  2.,  3.,  5.,  6.,  7.,  8.,  9., 10.])

- Un array de tres dimensiones con distribución binomial de 2 x 3 x 5, con probabilidad de 0.3 y número de pruebas igual a 10. Igual que antes, extrae sus valores únicos y guarda los datos en una variable.

In [30]:
arr4 = np.random.binomial(10, 0.3, size = (2,3,5))
arr4

array([[[1, 1, 2, 3, 1],
        [1, 1, 3, 4, 2],
        [5, 3, 3, 2, 3]],

       [[6, 3, 2, 3, 3],
        [3, 3, 1, 2, 3],
        [4, 4, 4, 3, 6]]])

In [31]:
arr4_unicos = np.unique(arr4)
arr4_unicos

array([1, 2, 3, 4, 5, 6])

### 3. En esta lección hemos aprendido algunos métodos de teorías de conjuntos. Usando los arrays de elementos únicos obtenidos en el ejercicio anterior realizad las siguientes operaciones:
- Elementos comunes entre los dos arrays

⚠️ Explicar cada uno de los outputs que os salgan. Que significa cada una de estas operaciones que hemos ido extrayendo?

In [32]:
np.intersect1d(arr3, arr4)

array([1., 2., 3., 5., 6.])

Al aplicar el método intersect1d estamos pidiendo que nos devuelva los valores que son comunes tanto en el array3 como en el array4.

- Unión de los dos arrays

In [33]:
np.union1d(arr3, arr4)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

Al aplicar el método union1d estamos pidiendo que nos devuelva la unión de los valores que tenemos tanto en el array3 como en el array4.

- ¿Qué elementos están en el array derivado de la distribución uniforme y no en los únicos de la distribución binomial? Extrae los valores númericos

In [34]:
np.setdiff1d(arr3, arr4)

array([ 0.,  7.,  8.,  9., 10.])

Al aplicar el método setdiff1d estamos pidiendo que nos devuelva los valores que si tenemos en el array3 pero no en el array4.

### 4. Cread dos arrays usando el método random.randint de Numpy con 80 elementos cada uno con números del 1-100, con los siguientes nombres array1 y array2.

In [40]:
array1 = np.random.randint(1, 100, (80))
array1

array([34,  3, 60, 58, 39, 97, 86, 77, 20, 54, 83,  9, 12, 42, 59, 24, 28,
       59, 61, 17,  5, 48, 77, 62, 99, 24, 20, 98, 32, 82, 90, 74, 60,  1,
        9, 11,  9, 47, 36, 79, 80, 55, 50,  7, 98, 99, 96, 50, 30, 35, 55,
       60, 98, 14, 13, 48, 84, 59, 45, 67, 32, 36, 51, 91, 11, 92, 43, 44,
       36, 43,  4, 94, 65,  6, 11, 12, 95, 82, 83, 66])

In [41]:
array2 = np.random.randint(1, 100, (80))
array2

array([87, 35, 15, 87, 30, 20, 42, 65, 95, 99, 12, 22, 22, 28, 84, 74, 18,
       41, 80, 11, 50, 69, 14, 31, 83,  7, 88, 22, 91, 81, 18, 38, 71, 58,
       30, 48, 57, 35, 23,  1, 23, 27,  1, 69, 52, 52, 24, 48, 64, 29, 81,
       74, 47, 63, 55, 81, 55, 49, 52,  8, 52, 64, 65, 89, 54, 50, 76, 48,
       17, 39, 47, 60, 88, 89, 53, 26,  3, 72, 38, 10])

- Extraed los valores únicos de cada uno de los arrays y los guardáis en variables en las que se les llame array1 y array2.

In [42]:
array1 = np.unique(array1)
array1

array([ 1,  3,  4,  5,  6,  7,  9, 11, 12, 13, 14, 17, 20, 24, 28, 30, 32,
       34, 35, 36, 39, 42, 43, 44, 45, 47, 48, 50, 51, 54, 55, 58, 59, 60,
       61, 62, 65, 66, 67, 74, 77, 79, 80, 82, 83, 84, 86, 90, 91, 92, 94,
       95, 96, 97, 98, 99])

In [43]:
array2 = np.unique(array2)
array2

array([ 1,  3,  7,  8, 10, 11, 12, 14, 15, 17, 18, 20, 22, 23, 24, 26, 27,
       28, 29, 30, 31, 35, 38, 39, 41, 42, 47, 48, 49, 50, 52, 53, 54, 55,
       57, 58, 60, 63, 64, 65, 69, 71, 72, 74, 76, 80, 81, 83, 84, 87, 88,
       89, 91, 95, 99])

- Identificad los elementos presentes en el array1 pero no en el array2 y asignarlo a una variable que se llame array3.

In [44]:
array3 = np.setdiff1d(array1, array2)
array3

array([ 4,  5,  6,  9, 13, 32, 34, 36, 43, 44, 45, 51, 59, 61, 62, 66, 67,
       77, 79, 82, 86, 90, 92, 94, 96, 97, 98])

- Identificad los elementos presentes en el array2 pero no en el array1 y asiganarlo a una variable que se llame array4.

In [45]:
array4 = np.setdiff1d(array2, array1)
array4

array([ 8, 10, 15, 18, 22, 23, 26, 27, 29, 31, 38, 41, 49, 52, 53, 57, 63,
       64, 69, 71, 72, 76, 81, 87, 88, 89])

- Identificad los elementos presentes en ambos arrays y asiganarlos a una variable que se llame array5.

In [46]:
array5 = np.intersect1d(array1, array2)
array5

array([ 1,  3,  7, 11, 12, 14, 17, 20, 24, 28, 30, 35, 39, 42, 47, 48, 50,
       54, 55, 58, 60, 65, 74, 80, 83, 84, 91, 95, 99])

- ¿Cuál es la relación que existe entre todos estos arrays? 💡 Pista 💡 Tendréis que usar las longitudes de cada uno de los arrays creados.

In [57]:
array1.size

56

In [58]:
array2.size

55

In [59]:
array3.size

27

In [60]:
array4.size

26

In [61]:
array5.size

29

In [62]:
array4.size + array5.size == array2.size

True

In [63]:
array3.size + array5.size == array1.size

True

In [64]:
array3.size + array4.size + array5.size == array1.size + array2.size - array5.size

True

In [66]:
array1.size - array3.size == array5.size == array2.size - array4.size

True

Si restamos los valores únicos del array1 a los valores que están en el array1 pero no el array2 es el resultado del array5 que son los valores que están en ambos (array1 y array2) y a su vez si restamos los valores únicos del array2 a los valores que están en el array2 pero no el array1 es el resultado del array5.

Happy coding 💪🏽