# Introducción a NumPy I

In [2]:
import numpy as np

### 1. Cread tres arrays: de una, dos y tres dimensiones.
   
Lo podéis hacer usando los métodos de random que hemos aprendido o a través de listas em algunos casos.

📌 Nota

El array de 2 dimensiones debe ser de 2 filas y 3 columnas

El array de 3 dimensiones debe ser de 2 matrices, 3 filas y 5 columnas

In [3]:
array1 = np.random.randint(0,100, (8))
array1

array([38, 92, 20, 49, 97, 20, 72,  2])

In [4]:
array2 = np.random.rand(2,3)
array2

array([[0.15594714, 0.83593522, 0.55943851],
       [0.24105356, 0.44424093, 0.34134939]])

In [5]:
array3 = np.random.random_sample((2,3,5))
array3

array([[[0.34411632, 0.80518516, 0.5508514 , 0.37510925, 0.83437406],
        [0.2201531 , 0.51316506, 0.67876969, 0.00126677, 0.03359639],
        [0.99884223, 0.84923485, 0.11428617, 0.73598833, 0.42793155]],

       [[0.07340349, 0.68457847, 0.71006196, 0.66208889, 0.1825129 ],
        [0.6681463 , 0.27747975, 0.70794892, 0.79122291, 0.34778823],
        [0.04797172, 0.93608393, 0.964382  , 0.5585787 , 0.06554305]]])

### 2. Chequead las propiedades básicas de cada array que os hayáis creado. Usad en una función que nos devuelva las propiedades de una array que le pasemos.

In [6]:
def propiedades(array):
    lista_propiedades = []
    lista_propiedades.append(array.shape)
    lista_propiedades.append(array.size)
    lista_propiedades.append(array.ndim)
    lista_propiedades.append(array.dtype)
    return lista_propiedades

In [7]:
print(f"El orden de las propiedades descritas, es forma, tamaño, dimension y tipo:", propiedades(array1))

El orden de las propiedades descritas, es forma, tamaño, dimension y tipo: [(8,), 8, 1, dtype('int64')]


In [8]:
print(f"El orden de las propiedades descritas, es forma, tamaño, dimension y tipo:", propiedades(array2))

El orden de las propiedades descritas, es forma, tamaño, dimension y tipo: [(2, 3), 6, 2, dtype('float64')]


In [9]:
print(f"El orden de las propiedades descritas, es forma, tamaño, dimension y tipo:", propiedades(array3))

El orden de las propiedades descritas, es forma, tamaño, dimension y tipo: [(2, 3, 5), 30, 3, dtype('float64')]


### 3. Cread una matriz identidad de dos dimensiones de 3 filas y 3 columnas.

In [10]:
array4 = np.identity(3)
array4

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [11]:
print(f"El orden de las propiedades descritas, es forma, tamaño, dimension y tipo:", propiedades(array4))

El orden de las propiedades descritas, es forma, tamaño, dimension y tipo: [(3, 3), 9, 2, dtype('float64')]


### 4. Cread una matriz de tres dimensiones de unos igual a la martiz de tres dimensiones creada en el primer ejercicio.

In [12]:
array5  = np.ones_like(array3)
array5

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

### 5. Es el momento de hacer algunas operaciones entre arrays
   
¿Se puede sumar el array de dos dimensiones que creamos en el primer ejecicios a la matriz identidad? ¿Por qué?

En caso de que no se puedan sumar, busca una solución para sumar una matriz identidad a otra. La solución puede ser crear un array nuevo.

Multiplicad la matriz identidad por la nueva matriz que os creasteis en el ejercicio anterior.

Dividid las dos matricess

In [13]:
array2

array([[0.15594714, 0.83593522, 0.55943851],
       [0.24105356, 0.44424093, 0.34134939]])

In [14]:
array4

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
print(f"El motivo por el que no podemos sumar las dos arrays, es porque tienen forma distinta.")
print(array2.shape)
print(array4.shape)

El motivo por el que no podemos sumar las dos arrays, es porque tienen forma distinta.
(2, 3)
(3, 3)


In [16]:
array6 = np.eye(3,3)
array6

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
array7 = np.add(array4,array6)
array7

array([[2., 0., 0.],
       [0., 2., 0.],
       [0., 0., 2.]])

In [18]:
np.multiply(array7, array4)

array([[2., 0., 0.],
       [0., 2., 0.],
       [0., 0., 2.]])

In [19]:
np.divide(array7, array4)

/var/folders/q5/d6h10gfs1b33l8qy7mdmhspw0000gq/T/ipykernel_79790/261659766.py:1: RuntimeWarning: invalid value encountered in true_divide
  np.divide(array7, array4)


array([[ 2., nan, nan],
       [nan,  2., nan],
       [nan, nan,  2.]])